# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: salon_user  # или ваше имя пользователя
  password: salon_password
  host: localhost

development:
  <<: *default
  database: beauty_salon_db

test:
  <<: *default
  database: beauty_salon_test

production:
  <<: *default
  database: beauty_salon_production